services:
  - type: web
    name: n8n
    env: docker
    plan: free
    autoDeploy: false
    dockerfilePath: Dockerfile
    disk:
      name: n8n_data
      mountPath: /home/node/.n8n
      sizeGB: 0.4
